/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_administrator_ndktest_MainActivity */

#ifndef _Included_com_example_administrator_ndktest_MainActivity
#define _Included_com_example_administrator_ndktest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_administrator_ndktest_MainActivity
 * Method:    getJNIString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_administrator_ndktest_MainActivity_getJNIString
  (JNIEnv *, jobject);

/*
 * Class:     com_example_administrator_ndktest_MainActivity
 * Method:    checkPassword
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_administrator_ndktest_MainActivity_checkPassword
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
